name: push_chat
description: "A new Flutter Simple Chat Applica on with Push Notification"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/
  
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: chat
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
